-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "form" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "pointsPerGame" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "selectedByPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
